# Generated by Django 5.2.7 on 2025-12-05 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0008_remove_profesor_grado_asignado_and_more'),
        ('core', '0002_gradoseccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', 'Primer Lapso'), ('2', 'Segundo Lapso'), ('3', 'Tercer Lapso')], max_length=1)),
                ('archivo_pdf', models.FileField(upload_to='boletines/')),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio general calculado', max_digits=5, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to='Usuarios.estudiante')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_emision'],
                'unique_together': {('estudiante', 'lapso')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaBoletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1', 'Primer Lapso'), ('2', 'Segundo Lapso'), ('3', 'Tercer Lapso')], max_length=1)),
                ('archivo_word', models.FileField(upload_to='plantillas_boletines/')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grado_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_boletin', to='core.gradoseccion')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida'],
                'unique_together': {('periodo', 'grado_seccion')},
            },
        ),
    ]
