# Generated by Django 5.2.7 on 2026-02-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_escolar', models.CharField(blank=True, help_text='Ejemplo: 2025-2026', max_length=20)),
                ('lapso', models.CharField(choices=[('1', 'Primer Lapso'), ('2', 'Segundo Lapso'), ('3', 'Tercer Lapso')], max_length=1)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletines/finales/')),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('es_definitivo', models.BooleanField(default=False, help_text='Si está marcado, se considera el boletín oficial cerrado.')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to='Usuarios.estudiante')),
            ],
            options={
                'verbose_name': 'Boletín Informativo',
                'verbose_name_plural': 'Boletines Informativos',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
