# Generated by Django 5.2.7 on 2026-02-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='boletines/finales/'),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='es_definitivo',
            field=models.BooleanField(default=False, help_text='Si está marcado, se considera el boletín oficial cerrado.'),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='periodo_escolar',
            field=models.CharField(blank=True, help_text='Ejemplo: 2025-2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='promedio_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
