# Generated by Django 5.2.7 on 2026-02-02 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletines', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boletin',
            name='grado_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines_historicos', to='core.gradoseccion'),
        ),
        migrations.AlterUniqueTogether(
            name='boletin',
            unique_together={('estudiante', 'lapso', 'periodo_escolar')},
        ),
    ]
