# Generated by Django 5.2.7 on 2026-01-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='archivo_word',
            field=models.FileField(blank=True, null=True, upload_to='boletines/'),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='boletines/'),
        ),
    ]
