# Generated by Django 5.2.7 on 2025-11-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('representante', 'Representante'), ('estudiante', 'Estudiante')], max_length=20),
        ),
    ]
