# Generated by Django 5.2.7 on 2026-01-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0008_remove_profesor_grado_asignado_and_more'),
        ('horarios', '0002_alter_horario_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', 'Primer Lapso'), ('2', 'Segundo Lapso'), ('3', 'Tercer Lapso')], max_length=1)),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, help_text='Primera nota parcial (0-20)', max_digits=5, null=True)),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, help_text='Segunda nota parcial (0-20)', max_digits=5, null=True)),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, help_text='Tercera nota parcial (0-20)', max_digits=5, null=True)),
                ('nota4', models.DecimalField(blank=True, decimal_places=2, help_text='Cuarta nota parcial (0-20)', max_digits=5, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio de las notas parciales', max_digits=5, null=True)),
                ('enviado', models.BooleanField(default=False, help_text='Indica si las calificaciones finales ya fueron enviadas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='Usuarios.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='horarios.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_registradas', to='Usuarios.profesor')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('estudiante', 'materia', 'lapso')},
            },
        ),
    ]
