# Generated by Django 5.2.7 on 2026-02-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0002_initial'),
        ('calificaciones', '0001_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='horarios.materia'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_registradas', to='Usuarios.profesor'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='calificaciones.calificacion'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('estudiante', 'materia', 'lapso')},
        ),
    ]
