# Generated by Django 5.2.7 on 2026-01-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alter_calificacion_enviado_alter_calificacion_nota1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='enviado',
            field=models.BooleanField(default=False, help_text='Indica si las calificaciones finales ya fueron enviadas'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Primera nota parcial (0-20)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Segunda nota parcial (0-20)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tercera nota parcial (0-20)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota4',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cuarta nota parcial (0-20)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promedio de las notas parciales', max_digits=5, null=True),
        ),
    ]
