# Generated by Django 5.2.7 on 2026-02-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del profesor sobre el estudiante en esta materia', null=True),
        ),
    ]
