# Generated by Django 5.2.7 on 2026-01-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_alter_calificacion_enviado_alter_calificacion_nota1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='enviado',
            field=models.BooleanField(default=False, help_text='Si es True, el registro queda bloqueado para edición'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-20', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-20', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-20', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota4',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-20', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente', max_digits=5, null=True),
        ),
    ]
