# Generated by Django 5.2.7 on 2026-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_alter_calificacion_enviado_alter_calificacion_nota1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Control de Nota'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota3',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota4',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='lapso',
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
