# Generated by Django 5.2.7 on 2025-11-06 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('grado_asignado', models.CharField(max_length=50)),
                ('tipo_profesor', models.CharField(choices=[('titular', 'Titular'), ('suplente', 'Suplente'), ('especialista', 'Especialista')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesores/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='representantes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
