# Generated by Django 5.2.7 on 2025-11-06 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_administrador_profesor_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='Usuarios.representante'),
        ),
    ]
