# Generated by Django 5.2.7 on 2026-02-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('graduado', 'Graduado'), ('retirado', 'Retirado'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('es_repitiente', models.BooleanField(default=False, help_text='Marcar si el estudiante está repitiendo el grado actual.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_profesor', models.CharField(choices=[('titular', 'Titular'), ('suplente', 'Suplente'), ('especialista', 'Especialista')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesores/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='representantes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
