# Generated by Django 5.2.7 on 2026-02-02 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('core', '0001_initial'),
        ('horarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.gradoseccion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesor',
            name='grado_secciones',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='core.gradoseccion'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='horarios.materia'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='representante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='Usuarios.representante'),
        ),
    ]
