# Generated by Django 5.2.7 on 2025-11-08 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_estudiante_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='profesor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantes_asignados', to='Usuarios.profesor', verbose_name='Profesor asignado'),
        ),
    ]
