# Generated by Django 5.2.7 on 2025-11-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_representante_profesor_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
    ]
