# Generated by Django 5.2.7 on 2025-11-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_remove_estudiante_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='edad',
        ),
    ]
