# Generated by Django 5.2.7 on 2025-11-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_remove_profesor_edad_remove_representante_edad'),
        ('core', '0002_gradoseccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nivel',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.gradoseccion'),
        ),
    ]
