# Generated by Django 5.2.7 on 2025-11-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_remove_estudiante_grado_remove_estudiante_nivel_and_more'),
        ('core', '0002_gradoseccion'),
        ('horarios', '0002_alter_horario_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='grado_asignado',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='profesor_asignado',
        ),
        migrations.AddField(
            model_name='profesor',
            name='grado_secciones',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='core.gradoseccion'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='horarios.materia'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
