# Generated by Django 5.2.7 on 2026-02-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_remove_profesor_grado_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='es_repitiente',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante está repitiendo el grado actual.'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('graduado', 'Graduado'), ('retirado', 'Retirado'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
