# Generated by Django 5.2.7 on 2025-11-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_remove_estudiante_grado_remove_estudiante_nivel_and_more'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.profesor'),
        ),
    ]
