# Generated by Django 5.2.7 on 2026-02-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Plantel')),
                ('codigo_dea', models.CharField(blank=True, max_length=50, verbose_name='Código DEA')),
                ('rif', models.CharField(blank=True, max_length=20, verbose_name='RIF')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institucion/logo/')),
                ('director', models.CharField(max_length=150, verbose_name='Director(a)')),
                ('subdirector', models.CharField(blank=True, max_length=150, verbose_name='Subdirector(a)')),
                ('slogan_boletin', models.CharField(default='Educando para el futuro', max_length=255, verbose_name='Slogan / Mensaje al pie')),
            ],
            options={
                'verbose_name': 'Configuración de la Institución',
                'verbose_name_plural': 'Configuración de la Institución',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('es_actual', models.BooleanField(default=False, verbose_name='¿Es el periodo activo?')),
            ],
            options={
                'verbose_name': 'Periodo Escolar',
                'verbose_name_plural': 'Periodos Escolares',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('representante', 'Representante'), ('estudiante', 'Estudiante')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20)),
                ('grado', models.CharField(choices=[('1', '1er grado'), ('2', '2do grado'), ('3', '3er grado'), ('4', '4to grado'), ('5', '5to grado'), ('6', '6to grado'), ('1', '1er año'), ('2', '2do año'), ('3', '3er año'), ('4', '4to año'), ('5', '5to año'), ('6', '6to año')], max_length=50)),
                ('seccion', models.CharField(choices=[('A', 'Sección A'), ('B', 'Sección B'), ('C', 'Sección C')], max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('docente_guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_asignadas', to='Usuarios.profesor')),
            ],
            options={
                'verbose_name': 'Grado y Sección',
                'verbose_name_plural': 'Grados y Secciones',
                'unique_together': {('nivel', 'grado', 'seccion')},
            },
        ),
    ]
