# Generated by Django 5.2.7 on 2025-11-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20)),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(choices=[('A', 'Sección A'), ('B', 'Sección B'), ('C', 'Sección C')], max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
