# Generated by Django 5.2.7 on 2026-02-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_estudiante_es_repitiente_estudiante_estatus'),
        ('core', '0003_alter_gradoseccion_options_alter_gradoseccion_grado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Plantel')),
                ('codigo_dea', models.CharField(blank=True, max_length=50, verbose_name='Código DEA')),
                ('rif', models.CharField(blank=True, max_length=20, verbose_name='RIF')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institucion/logo/')),
                ('director', models.CharField(max_length=150, verbose_name='Director(a)')),
                ('subdirector', models.CharField(blank=True, max_length=150, verbose_name='Subdirector(a)')),
                ('slogan_boletin', models.CharField(default='Educando para el futuro', max_length=255, verbose_name='Slogan / Mensaje al pie')),
            ],
            options={
                'verbose_name': 'Configuración de la Institución',
                'verbose_name_plural': 'Configuración de la Institución',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('es_actual', models.BooleanField(default=False, verbose_name='¿Es el periodo activo?')),
            ],
            options={
                'verbose_name': 'Periodo Escolar',
                'verbose_name_plural': 'Periodos Escolares',
            },
        ),
        migrations.AddField(
            model_name='gradoseccion',
            name='docente_guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_asignadas', to='Usuarios.profesor'),
        ),
    ]
